### ISSUE TITLE
DeltaPlugin and Habasi merged plugins

### ISSUE THREAD

**Issue by benjaminwinger** [alvazir/habasi#1]
I just saw this recently and had a question about something in the release announcement:

> There are also record mergers: TES3Merge, DeltaPlugin, Merged Lands, all the leveled lists mergers etc. I only use leveled lists merging, though I've made sure that all of those(tested with TES3Merge, DeltaPlugin, Jobasha) would continue working with merged plugins the same way as with unmerged. It's done by keeping different variants of mergeable records in a merged plugin by default.

Are you sure that this works with DeltaPlugin? While I can't speak for other tools, DeltaPlugin uses a custom internal representation of the plugin data which, among other things, stores records in a mapping using the record ids as keys, so it will discard all but the last one it reads (much like OpenMW does when loading them).

Also, I'd love to help cultivate more of a rust ecosystem for openmw/morrowind libraries. Unfortunately, DeltaPlugin's internals make that difficult for the most part, but I can offer up the [openmw-cfg](https://crates.io/crates/openmw-cfg) crate in case you find it helpful, which is a library providing functions that interact with the openmw VFS and plugin load order (and I recently added support for VFS files in BSA archives via [bsatool_rs](https://github.com/arviceblot/bsatool_rs).

**Comment by alvazir** [comment]
* I am sorry for my mistake. I suppose I was over enthusiastic when checking utilities in the pre-publishing fever. I saw tes3cmd and TES3Merge(? I'm not sure now :-/) work with merged plugins and probably skipped or misinterpreted DeltaPlugin check results. I will change relevant descriptions to something like that:
"DeltaPlugin processes records the same way as both engines, e.g. discards different variants of mergeable records except the last one. To be able to use both utilities consider using additional openmw.cfg file ...<here goes description to run DeltaPlugin first with additional config, then Habasi>"

* I've looked at both crates actually. Both were easy to plug in. I've had some concerns with performance, but the main deciding factor was the license. I've based my licensing decision on rust's defaults. I'd probably use GPL next time because it looks great for programs. Libraries are a bit different. I didn't like being forced to change my program's license from MIT to GPL by using those crates :-\

**Comment by benjaminwinger** [comment]
No problem.

> the main deciding factor was the license. I've based my licensing decision on rust's defaults. I'd probably use GPL next time because it looks great for programs. Libraries are a bit different. I didn't like being forced to change my program's license from MIT to GPL by using those crates :-\

Yes I suppose that's true. bsatool_rs is I think based heavily on the openmw BSA code, so its license follows openmw's. openmw-cfg I'd licensed GPL mostly because that's what I usually use, but for a small library I don't feel strongly about the license. I could make the bsa part of openmw-cfg a feature and re-license it MIT so that you don't pull in any GPL code if that feature isn't enabled.

> I've had some concerns with performance

What sort of performance concerns? For the most part, I don't think it's particularly performance-intensive, with maybe the exception of the VFS lookups if you're doing a lot of work with the VFS (does it take a noticeable amount of time just to look up the plugin paths?). There's also a small but important optimization I'd included in [the python version](https://gitlab.com/portmod/portmod/-/blob/c03ec398011ee8b1768d8caff579a0357e2cb284/portmodlib/fs.py#L176-184) of that case insensitive lookup algorithm which never made it to openmw-cfg, so it could certainly be improved.

**Comment by alvazir** [comment]
> Yes I suppose that's true. bsatool_rs is I think based heavily on the openmw BSA code, so its license follows openmw's. openmw-cfg I'd licensed GPL mostly because that's what I usually use, but for a small library I don't feel strongly about the license. I could make the bsa part of openmw-cfg a feature and re-license it MIT so that you don't pull in any GPL code if that feature isn't enabled.

That'd be awesome!

> What sort of performance concerns? For the most part, I don't think it's particularly performance-intensive, with maybe the exception of the VFS lookups if you're doing a lot of work with the VFS (does it take a noticeable amount of time just to look up the plugin paths?). There's also a small but important optimization I'd included in [the python version](https://gitlab.com/portmod/portmod/-/blob/c03ec398011ee8b1768d8caff579a0357e2cb284/portmodlib/fs.py#L176-184) of that case insensitive lookup algorithm which never made it to openmw-cfg, so it could certainly be improved.

1. openmw-cfg
As far as I remember it should be related to VFS. I've tested against ~600 plugins/1000-2000 directories. It took ~2 seconds on my machine. [Parallel read_dir](https://github.com/alvazir/jobasha/blob/73e71fbabf2d5be25c8fc7cb2a9d9c96f5bb2f11/src/get_plugins.rs#L88) helped me to reduce the time to ~20ms.
2. bsatool-rs
Bsatool-rs makes excessive calls when reading BSA metadata. It may be reduced ~20x. I may look and make PR to fix the issue. I've had a pretty specific request to read multiple BSA as fast as possible and so finished creating my own "[lib](https://github.com/alvazir/habasi/blob/ba407d8cbe190b19876439132965f4372f77ffe2/src/assets/bsa.rs#L16)" with the help of that awesome UESP page and linked Interntet Archive page.

**Comment by alvazir** [comment]
And done. Made [PR](https://github.com/arviceblot/bsatool_rs/pull/47) to bsatool_rs with improved offset reading time.

**Comment by benjaminwinger** [comment]
> As far as I remember it should be related to VFS. I've tested against ~600 plugins/1000-2000 directories. It took ~2 seconds on my machine. [Parallel read_dir](https://github.com/alvazir/jobasha/blob/73e71fbabf2d5be25c8fc7cb2a9d9c96f5bb2f11/src/get_plugins.rs#L88) helped me to reduce the time to ~20ms.

That is kind of slow. I did a quick benchmark and for me it's running in about 100ms, but that's with a much smaller load order on a fast ssd. I tried on a networked hard drive and it increased to 1.7 seconds. But with parallel reads that went down to ~200ms (and 15ms on the ssd).

Still slower than what you're doing in jobasha because it's doing multiple passes, but I only have so much time right now. I think I'd rather write a generic `find_files` function than optimize just for plugins, that way other stuff can benefit (I think it would mostly just be [groundcoverify via delta-plugin](https://gitlab.com/bmwinger/groundcoverify/-/blob/8a0253026a896b3578c8d6b21ed1288647c77ef2/groundcoverify.py#L171-173) right now).

**Comment by alvazir** [comment]
My information may be slightly outdated as I used openmw-cfg v0.3.0 in May. I'd probably made something wrong when testing. 

I've just checked and seen GPL or MIT license choice on oenmw-cfg v0.5.0 crate. That's awesome!

I suppose the issue may be closed.
