### ISSUE TITLE
Implicit OpenMW Data folder is not used

### ISSUE THREAD

**Issue by magicaldave** [alvazir/habasi#3]
OpenMW has a 'hidden' data path used by the OpenMW-CS which is not listed in the main openmw.cfg. This results in plugins which openmw knows how to find, being invisible to Habasi.

In almost all cases, the actual path used matches https://openmw.readthedocs.io/en/latest/reference/modding/paths.html#savegames with the exception that the subdir is `data` instead of `saves`. 

For example on my system it's: `/home/sk3shun-8/.local/share/openmw/data/`

Since these are consistent across platforms it should be relatively simple to also read this directory in the case that an openmw.cfg load order is detected.

**Comment by alvazir** [comment]
Added the folder.

It works implicitly. You'll see the message that it was added to the list of data dirs. Otherwise verbose mode shows that it was not found(Android?). Plugins from this folder have the highest priority and will be added instead of similar plugins from other directories. Hopefully that's the same logic as OpenMW uses.

**Comment by magicaldave** [comment]
Thanks so much for the quick assists! 
All seems well. Implicit dir works but its only priority should be after the initial `Data Files` folder, in effect just the second one used and not the final one. I don't think it'll really affect much though, I just happened to notice it because some WIP plugins I still had there weren't included.

**Comment by alvazir** [comment]
I've rechecked. Perhaps I've used bad wording.

Let's imagine we have **Plugin** plugin.omwaddon in directory **Directory**. Both **Directory** and **Plugin** are listed in openmw.cfg. Then we place **Plugin** into "~/.local/share/openmw/data" **CS_DATA_DIR** folder. This way, if I understood things right, **Plugin** should be read from **CS_DATA_DIR**. That's what my testing shows. In other words, hidden **CS_DATA_DIR** is added as a very last "data=" folder.

Should the logic be like I displayed? Please recheck then. Or please tell me how it should work :-) I've never actually used that folder for loading plugins from it, so I may be missing something.

**Comment by magicaldave** [comment]
Oh. You know. I'm sorry, I apologize if I wasted your time. That's perfect :D I had a misunderstanding from reading a smaller log. 

Example run from earlier today:

```
[12:19:17.184 I] Adding data directory /usr/share/games/openmw/resources/vfs
[12:19:17.184 I] Adding data directory /usr/share/games/openmw/resources/vfs-mw
[12:19:17.184 I] Adding data directory /home/sk3shun-8/Games/Starwind/drive_c/GOG Games/Morrowind/Data Files
[12:19:17.184 I] Adding data directory /home/sk3shun-8/Games/Starwind/drive_c/GOG Games/Morrowind/Naboo
[12:19:17.184 I] Adding data directory /home/sk3shun-8/.local/share/openmw/projects
[12:19:17.184 I] Adding data directory /home/sk3shun-8/.local/share/openmw/data
```
Implicit data dir from CS does indeed load *last*.

the `vfs` ones and `projects` are never actually used for plugins (well, they could be, but that's horrendous) so yes this is great, thank you.
