### ISSUE TITLE
TES3::FORM subrecord causes failures

### ISSUE THREAD

**Issue by magicaldave** [alvazir/habasi#4]
OpenMW extended the TES3 subrecord to also allow a FORM subrecord indicating the format version of omwaddon; these tags cause habasi to fail when such plugins are encountered.

Failed to process list "MergedLoadOrder.esp, no_dry_run, use_load_order, exclude_deleted_records, complete_replace, strip_masters, ignore_errors, no_insufficient_merge"

Caused by:
    0: Failed to process plugin
    1: Failed to load plugin "/home/sk3shun-8/openmw/openmw_mods/crassified navigation/Crassified Navigation.esp": Unexpected Tag: TES3::FORM
        Fix the problem or add "--ignore-important-errors"(may rarely cause unexpected behaviour) to ignore

**Comment by alvazir** [comment]
Fix was added. Ignoring it for now.

Record parsing is delegated to tes3 library. I suppose I have to ask Greatness7 to add support for such records in tes3 library.

**Comment by magicaldave** [comment]
Yes, we've talked a bit about this as regards LUAL and this one also. They suggested it might be a valid idea to just fork a superset of tes3 which supports omwaddon extensions. I dislike the idea somewhat as that's a lot to maintain just for what amounts to one full record and one subrecord, but it's only getting worse :D

Thanks again.
